CREATE TABLE chats (
    chat_id BIGINT PRIMARY KEY
);

CREATE TABLE links (
    id BIGSERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    chat_id BIGINT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
    last_checked_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE link_tags (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    link_id BIGINT REFERENCES links(id) ON DELETE CASCADE,
    tag VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX links_unique_chat_url ON links(chat_id, url);
CREATE INDEX links_url ON links(url);



